// const productCards = [
//     {
//         id: 1,
//         image: "../images/product-img1.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "1",
//         pawns: "4",
//         price: "30000",
//         inStock: true,
//     },
//     {
//         id: 2,
//         image: "../images/product-img2.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "3",
//         pawns: "4",
//         price: "40000",
//         inStock: false,
//     },
//     {
//         id: 3,
//         image: "../images/product-img3.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "7",
//         pawns: "4",
//         price: "20000",
//         inStock: true,
//     },
//     {
//         id: 4,
//         image: "../images/product-img1.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "9",
//         pawns: "4",
//         price: "20000",
//         inStock: true,
//     },
//     {
//         id: 5,
//         image: "../images/product-img3.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "8",
//         pawns: "4",
//         price: "25000",
//         inStock: true,
//     },
//     {
//         id: 6,
//         image: "../images/product-img2.png",
//         title: "Кот полосатый",
//         color: "Коричневый окрас",
//         age: "3.5",
//         pawns: "4",
//         price: "10000",
//         inStock: false,
//     },
// ];

// export default productCards
// // console.log(products);